name: Test Website builds correctly

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Jekyll and theme
      - name: Install Jekyll and the base theme
        run: |
            echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
            echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
            echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            gem install jekyll bundler
            gem install jekyll-theme-cayman

      # Build site
      - name: Build the site.
        run: jekyll build
